#APP_KEY: "1m6669bo04p2a0m"
#APP_SECRET: "uzaq2a5kfma5gd6"
#ACCESS_TOKEN: "10pq5a9lv2chgib1"
#ACCESS_TOKEN_SECRET: "aeyxidjmuqyq8bh"
#USER_ID: "331871441"

S3_BUCKET_NAME: 'makers-app-images'
S3_KEY: 'AKIAJAKUMWFODSYHDATA'
S3_SECRET: '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'
